In [1]:
import pandas as pd
import numpy as np

In [61]:
pd.options.display.float_format = '{:,.2f}'.format

### Problema 1
Vamos praticar gerar matrizes e fazer operações com as linhas e colunas:

(a) Crie uma matriz A com as dimensões (5, 4) e elementos aleatórios variando entre 0 e 50, com o 50 incluso;

__Dica:__ Utilize as funções `np.random.randint` e `np.reshape`

(b) Retorne a média do vetor

(c) Retorne os menores valores de cada coluna;

(d) Retorne os maiores valores de cada linha.

In [40]:
#A
np.random.seed(3)
matrix = np.random.randint(0, 51, size=(5, 4))
# OU
matrix2 = np.random.randint(0, 51, size=20).reshape(5,4)
matrix,matrix2

(array([[42, 24,  3,  8],
        [ 0, 21, 19, 10],
        [43, 41, 10, 21],
        [38, 32, 20, 44],
        [29, 39, 14, 26]]),
 array([[17, 26, 22,  2],
        [ 2,  1, 26,  5],
        [40, 46, 33, 29],
        [42, 24,  7, 43],
        [33, 15, 48, 37]]))

In [41]:
#B
matrix.mean(),np.mean(matrix)

(24.2, 24.2)

In [42]:
#C
np.min(matrix, axis=0)

array([ 0, 21,  3,  8])

In [43]:
#D
np.max(matrix, axis=1)

array([42, 21, 43, 44, 39])

### Problema 2

Crie um objeto DataFrame que contenha os dados da tabela abaixo, os quais se referem ao peso, altura e idade de cinco pessoas:


| Peso (kg) | Altura (cm) | Idade (anos) |
|-----------|-------------|--------------|
|  47 | 161	| 31 |
|  80 | 170	| 21 |
|  60 | 175	| 16 |
|  90 | 162	| 28 |
| 100 | 185	| 23 |
| 147 | 189 | 32 |

Com base no DataFrame criado, realize o que for pedido nos itens abaixo:

(a) Visualize apenas os dados da coluna que contém a altura das pessoas;

(b) Obtenha a idade média das pessoas;

(c) Obtenha os dados das pessoas que estão abaixo da altura média;

(d) Crie um nova coluna no DataFrame que contenha o IMC (Índice de Massa Corporal) de cada pessoa;

__Obs.:__ A fórmula para o IMC é dada por IMC = Peso/(Altura)² com o peso em kg e a altura em metros.

(e) Remova a coluna que contém a idade das pessoas;

(f) Crie uma nova coluna chamada Classificação, que contenha a classificação de cada indivíduo, de acordo com o seu IMC. Para isso, consulte a tabela abaixo.

| IMC             | Classificação |
|-----------------|---------------|
Menor que 18,5    | Subpeso |
Entre 18,5 e 24,9 | Normal |
Entre 25,0 e 29,9 | Sobrepeso |
Entre 30,0 e 39,9 | Obesidade Grau I |
Maior que 40,0    | Obesidade Grau II |

(g) Salve esses dados do DataFrame em um arquivo csv.

In [112]:
df_clipboard = pd.read_clipboard()
tabela = df_clipboard.copy()
tabela

Peso (kg)  Altura (cm)  Idade (anos)
0         47          161            31
1         80          170            21
2         60          175            16
3         90          162            28
4        100          185            23
5        147          189            32

In [113]:
#A
tabela[["Altura (cm)"]]

Altura (cm)
0          161
1          170
2          175
3          162
4          185
5          189

In [114]:
#B
tabela[["Idade (anos)"]].mean()

Idade (anos)   25.17
dtype: float64

In [115]:
#C
filtro = tabela["Altura (cm)"].mean()
tabela[tabela["Altura (cm)"] < filtro]

Peso (kg)  Altura (cm)  Idade (anos)
0         47          161            31
1         80          170            21
3         90          162            28

In [116]:
tabela

Peso (kg)  Altura (cm)  Idade (anos)
0         47          161            31
1         80          170            21
2         60          175            16
3         90          162            28
4        100          185            23
5        147          189            32

In [117]:
#D Crie um nova coluna no DataFrame que contenha o IMC (Índice de Massa Corporal) de cada pessoa;
# Obs.: A fórmula para o IMC é dada por IMC = Peso/(Altura)² com o peso em kg e a altura em metros.

tabela["IMC"] = (tabela["Peso (kg)"])/(tabela["Altura (cm)"]/100)**2

In [118]:
tabela

Peso (kg)  Altura (cm)  Idade (anos)   IMC
0         47          161            31 18.13
1         80          170            21 27.68
2         60          175            16 19.59
3         90          162            28 34.29
4        100          185            23 29.22
5        147          189            32 41.15

In [126]:
#E Remova a coluna que contém a idade das pessoas;
tabela2 = tabela.copy()
tabela2.drop(columns=['Idade (anos)'],axis=1, inplace=True)
tabela2

Peso (kg)  Altura (cm)   IMC
0         47          161 18.13
1         80          170 27.68
2         60          175 19.59
3         90          162 34.29
4        100          185 29.22
5        147          189 41.15

In [132]:
tabela2.drop(columns='Classificação', axis=1, inplace=True)

In [139]:
#F Crie uma nova coluna chamada Classificação, que contenha a classificação de cada indivíduo, de acordo com o seu IMC.
# Para isso, consulte a tabela abaixo.

def classificar(x):

    if x<18.5:
        return 'Subpeso'
    elif x<=24.9:
        return 'Normal'
    elif x<=29.9:
        return 'Sobrepeso'
    elif x<=39.9:
        return 'Obesidade Grau 1'
    else:
        return 'Obesidade Grau 2'

tabela2['Classificação'] = tabela2['IMC'].transform(classificar)
tabela2


Peso (kg)  Altura (cm)   IMC     Classificação
0         47          161 18.13           Subpeso
1         80          170 27.68         Sobrepeso
2         60          175 19.59            Normal
3         90          162 34.29  Obesidade Grau 1
4        100          185 29.22         Sobrepeso
5        147          189 41.15  Obesidade Grau 2

In [140]:
#G Salve esses dados do DataFrame em um arquivo csv.

tabela2.to_csv('arquivo_prova_IMC.csv')

### Problema 3

O arquivo avocado.xlsx consiste em um dataset que contém dados sobre vendas de abacates  em diversas regiões dos Estados Unidos. Essa dataset contém as seguintes colunas:

| Coluna | Descrição |
|--------|-----------|
| Date | data da observação |
| AveragePrice | preço médio de um único abacate |
| year | ano |
| region | cidade ou região da observação |
| Total Volume | volume total de abacates vendidos |

Além das informações acima, contidas no arquivo avocado.xlsx, o tipo do abacate (convencional ou orgânico) também seria uma informação importante para a sua análise. Suponhamos que você conseguiu essas informações para cada uma das observações do arquivo avocado.csv, na mesma ordem, e salvou-as no arquivo avocado_type.xlsx. Portanto, tudo o que você precisa é juntar esses dois arquivos em um mesmo DataFrame.

Com o DataFrame criado, obtenha o que é solicitado nos itens elencados abaixo:




In [251]:
avog = pd.read_csv('data/avocado.csv', delimiter=';')
avot = pd.read_excel('data/avocado_type.xlsx')
avot.shape, avog.shape

((18249, 1), (18249, 5))

In [252]:
avog['Type'] = avot['type']
avog

Date  AveragePrice  Total Volume  year            region  \
0      2015-12-27          1.33     64,236.62  2015            Albany   
1      2015-12-20          1.35     54,876.98  2015            Albany   
2      2015-12-13          0.93    118,220.22  2015            Albany   
3      2015-12-06          1.08     78,992.15  2015            Albany   
4      2015-11-29          1.28     51,039.60  2015            Albany   
...           ...           ...           ...   ...               ...   
18244  2018-02-04          1.63     17,074.83  2018  WestTexNewMexico   
18245  2018-01-28          1.71     13,888.04  2018  WestTexNewMexico   
18246  2018-01-21          1.87     13,766.76  2018  WestTexNewMexico   
18247  2018-01-14          1.93     16,205.22  2018  WestTexNewMexico   
18248  2018-01-07          1.62     17,489.58  2018  WestTexNewMexico   

               Type  
0          orgânico  
1      convencional  
2      convencional  
3          orgânico  
4          orgânico  
...             ...  
18244  convencional  
18245  convencional  
18246  convencional  
18247  convencional  
18248  convencional  

[18249 rows x 6 columns]

(a) A quantidade de abacates do tipo convecional e do tipo orgânico.

In [253]:
avog.groupby('Type')['Type'].count()

Type
convencional    9114
orgânico        9135
Name: Type, dtype: int64


(b) A quantidade de registros (linhas) de abacates vendidos para cada região ordenada da maior venda para a menor.

(c) Para que todos os labels das colunas fiquem padronizados, renomeie aqueles que estão iniciando em letra minúscula para que iniciem em letra maiúscula, trocando espaço por _ e adicionando _ como separação de texto.

In [254]:
avog.columns

Index(['Date', 'AveragePrice', 'Total Volume', 'year', 'region', 'Type'], dtype='object')

In [255]:
avog.rename({'AveragePrice':'Average_Price','Total Volume':'Total_Volume','year':'Year','region':'Region'},axis=1, inplace=True)
avog

Date  Average_Price  Total_Volume  Year            Region  \
0      2015-12-27           1.33     64,236.62  2015            Albany   
1      2015-12-20           1.35     54,876.98  2015            Albany   
2      2015-12-13           0.93    118,220.22  2015            Albany   
3      2015-12-06           1.08     78,992.15  2015            Albany   
4      2015-11-29           1.28     51,039.60  2015            Albany   
...           ...            ...           ...   ...               ...   
18244  2018-02-04           1.63     17,074.83  2018  WestTexNewMexico   
18245  2018-01-28           1.71     13,888.04  2018  WestTexNewMexico   
18246  2018-01-21           1.87     13,766.76  2018  WestTexNewMexico   
18247  2018-01-14           1.93     16,205.22  2018  WestTexNewMexico   
18248  2018-01-07           1.62     17,489.58  2018  WestTexNewMexico   

               Type  
0          orgânico  
1      convencional  
2      convencional  
3          orgânico  
4          orgânico  
...             ...  
18244  convencional  
18245  convencional  
18246  convencional  
18247  convencional  
18248  convencional  

[18249 rows x 6 columns]

(d) Essa dado possui duplicados? Se sim, remova-os do dataset.

In [256]:
avog.duplicated().sum()
# avog.shape

0

(e) Retire dos dados a região 'TotalUS'

In [269]:
avog2.columns

Index(['Date', 'Average_Price', 'Total_Volume', 'Year', 'Region', 'Type'], dtype='object')

In [284]:
avog2=avog.copy()
avog2 = avog2.set_index('Region')
avog2 = avog2.drop(index='TotalUS')
avog2.reset_index(inplace=True)

# outra forma de se fazer
df_remove = df_avocado_csv.loc[(df_avocado_csv['Region'] == 'TotalUS')]
df_avocado_csv.drop(df_remove.index)

(17911, 6)

(g) Apresente as regiões que mais venderam abacate em todo o período em ordem decrescente.

In [301]:
avog2.groupby(['Region'])[['Total_Volume']].sum().sort_values('Total_Volume', ascending=False).head(10)

Total_Volume
Region                       
West         1,086,779,155.75
California   1,028,981,653.17
SouthCentral 1,011,279,618.83
Northeast      713,280,909.56
Southeast      615,238,409.11
GreatLakes     589,642,549.29
Midsouth       508,349,357.20
LosAngeles     507,896,547.63
Plains         311,188,529.11
NewYork        240,734,127.53

(h) Calcule o volume total de abacates vendidos para cada tipo e ano.

In [307]:
avog2.groupby(['Type', 'Year'])[['Total_Volume']].sum().sort_values('Year', ascending=False)

Total_Volume
Type         Year                 
convencional 2018   433,710,441.83
orgânico     2018   425,395,644.21
convencional 2017 1,505,463,914.14
orgânico     2017 1,564,148,221.75
convencional 2016 1,538,913,526.12
orgânico     2016 1,462,817,222.93
convencional 2015 1,405,835,526.60
orgânico     2015 1,322,377,914.02

(f) existe alguma região que foi a maior responsável pela queda na produção de 2018?

In [367]:
avog3.columns

Index(['Year', 'Total_Volume', 'Region'], dtype='object')

In [370]:
avog3=avog.copy()
avog3 = avog3.set_index('Year')
avog3 = avog3.drop(labels=['Date','Average_Price', 'Type'], axis=1)
avog3 = avog3.drop(index=[2015,2016])
avog3.reset_index(inplace=True)

In [ ]:
pd.set_option('display.max_columns', None) # or 1000.
pd.set_option('display.max_rows', None) # or 1000.
pd.set_option('display.max_colwidth', -1) # or 199.

In [371]:
avog3.pivot_table(index='Region',values='Total_Volume', columns=['Year'], aggfunc='sum').head()

Year                         2017          2018
Region                                         
Albany              5,231,581.78  1,541,986.17 
Atlanta             28,815,119.98 8,231,422.45 
BaltimoreWashington 41,015,634.46 12,158,903.00
Boise               4,760,561.31  1,214,759.57 
Boston              30,610,672.16 8,637,005.96

(g) Qual cidade menos faturou com a venda de abacates?

In [351]:
avog2['Faturamento']=avog2['Average_Price']*avog2['Total_Volume']
avog2.groupby(['Region'])[['Faturamento']].sum().sort_values('Faturamento', ascending=True).head(5)

Faturamento
Region                  
Syracuse   15,205,192.60
Boise      15,346,666.47
Spokane    17,156,485.66
Louisville 17,495,546.93
Albany     21,766,723.75

### Problema 4

Com base no dataset 'Video_Games_Sales.csv' responda:


In [353]:
df = pd.read_csv('data/Video_Games_Sales.csv', delimiter=';')


(a) Quantos jogos existem em cada genero?


In [358]:
df.shape

(16719, 16)

In [360]:
df.head()

Name Platform  Year_of_Release         Genre Publisher  \
0  Wii Sports                Wii     2,006.00          Sports        Nintendo   
1  Super Mario Bros.         NES     1,985.00          Platform      Nintendo   
2  Mario Kart Wii            Wii     2,008.00          Racing        Nintendo   
3  Wii Sports Resort         Wii     2,009.00          Sports        Nintendo   
4  Pokemon Red/Pokemon Blue  GB      1,996.00          Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  Critic_Score  \
0 41.36     28.96     3.77      8.45         82.53         76.00           
1 29.08     3.58      6.81      0.77         40.24         nan             
2 15.68     12.76     3.79      3.29         35.52         82.00           
3 15.61     10.93     3.28      2.95         32.77         80.00           
4 11.27     8.89      10.22     1.00         31.37         nan             

   Critic_Count  User_Score  User_Count Developer Rating  
0 51.00         8.00        322.00       Nintendo  E      
1 nan           nan         nan          NaN       NaN    
2 73.00         8.30        709.00       Nintendo  E      
3 73.00         8.00        192.00       Nintendo  E      
4 nan           nan         nan          NaN       NaN

In [366]:
df.groupby('Genre')[['Name']].count()

Name
Genre             
Action        3370
Adventure     1303
Fighting      849 
Misc          1750
Platform      888 
Puzzle        580 
Racing        1249
Role-Playing  1500
Shooter       1323
Simulation    874 
Sports        2348
Strategy      683

(b) Temos duplicados nesses dados? E nulos?

In [381]:
df.isna().sum()

Name               2   
Platform           0   
Year_of_Release    269 
Genre              2   
Publisher          54  
NA_Sales           0   
EU_Sales           0   
JP_Sales           0   
Other_Sales        0   
Global_Sales       0   
Critic_Score       8582
Critic_Count       8582
User_Score         9129
User_Count         9129
Developer          6623
Rating             6769
dtype: int64

In [380]:
df.notnull().sum()

Name               16717
Platform           16719
Year_of_Release    16450
Genre              16717
Publisher          16665
NA_Sales           16719
EU_Sales           16719
JP_Sales           16719
Other_Sales        16719
Global_Sales       16719
Critic_Score       8137 
Critic_Count       8137 
User_Score         7590 
User_Count         7590 
Developer          10096
Rating             9950 
dtype: int64

In [378]:
df.isnull().sum()

Name               2   
Platform           0   
Year_of_Release    269 
Genre              2   
Publisher          54  
NA_Sales           0   
EU_Sales           0   
JP_Sales           0   
Other_Sales        0   
Global_Sales       0   
Critic_Score       8582
Critic_Count       8582
User_Score         9129
User_Count         9129
Developer          6623
Rating             6769
dtype: int64

In [376]:
df.duplicated().sum()

0

(b) Quantos jogos de cada publisher receberam nota acima de 9 na avaliação dos usuarios?

In [395]:
df[df[['User_Score']] > 9].count()

Name               0  
Platform           0  
Year_of_Release    0  
Genre              0  
Publisher          0  
NA_Sales           0  
EU_Sales           0  
JP_Sales           0  
Other_Sales        0  
Global_Sales       0  
Critic_Score       0  
Critic_Count       0  
User_Score         184
User_Count         0  
Developer          0  
Rating             0  
dtype: int64


(c) Faça uma tabela que mostre o total vendido por ano por pais/globalmente de cada publisher? Você consegue observar algum padrão? Com se comportaram as vendas na América do Norte (NA) ao longo do tempo? O mesmo foi visto nos demais lugares? 



(d) Qual foi jogo mais vendido na união européia? De que ano ele é e qual a editora?



(e) Quantos % os generos ['Racing', 'Sports', 'Shooter'] representam na base de dados? 

(f) Qual plataforma vendeu menos globalmente? obs: imprimir somente o nome

### Problema 5
A pasta 'data/datasus' contém informações sobre casos de dengue e tabelas auxiliares. <br>

| Tabela | Conteúdo |
|--------|----------|
| Dengue | Quantidade de casos por município |
| Agua | Quantidade de residências em cada município por tipo o abastecimento de água |
| InstalacoesSanitarias | Quantidade de residências em cada município por tipo de rede de esgoto |
| Pib | PIB per capita de cada município |
| Municipios | Relaciona o id_municipio com seu nome e estado |
| Populacao | Quantidade de pessoas morando em áreas urbanas, rurais e população total por município |
| Sexo | Quantidade de pessoas por sexo em cada município |

(a) Calcular o número de casos de dengue por cada estado apresentando os dados em ordem decrescente.


(b) Utilizando o dataset InstalacoesSanitarias.csv, determine o número de pessoas que não possuem meio sanitário algum de descarte de dejetos por estado.

(c) Crie uma coluna com a posição de ranking considerando o PIB. Os maiores PIB devem ter os menores valores de ranking.

(d) Qual o PIB dos 5 municípios com mais casos de dengue e sua posição no ranking?